openapi: 3.0.0
info:
  title: Master data API
  version: 0.1.9
servers:
  - url: https://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: https://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /api/rest/v1/turbines/{turbineId}:
    get:
      operationId: getTurbineById
      summary: Returns a list of turbines.
      parameters:
        - name: turbineId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Turbine for given ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  name:
                    type: string
                  maxCapacity:
                    type: integer
                    format: int64
                    minimum: 1
                  lastModifiedAt:
                    type: string
                    format: date-time
                  createdAt:
                    type: string
                    format: date-time
        '404':
          description: No turbine found for given ID